name: Run Azure Login with OIDC
on: [push]

defaults:
  run:
    shell: bash
    working-directory: iac
    
permissions:
      id-token: write
      contents: read
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          az account get-access-token
      - name: 'Run Terraform apply'
        uses: dflook/terraform-apply@v1
        
       
          
